---
- name: NFS | Install packages to enable NFS support
  apt: pkg={{ item }} state=installed
  tags: aptget
  sudo: true
  with_items:
    - nfs-common
    - portmap
    - cachefilesd

- name: NFS | Enable NFS caching
  lineinfile: dest=/etc/default/cachefilesd regexp="^[#|;]?RUN=yes" insertafter="^[#|;]?RUN=yes" line="RUN=yes"
  tags: php
  sudo: true

