---
- name: Vim Config | Check if ~/.webscope-vim folder exists
  raw: ls ~/.webscope-vim
  register: webscope_vim_folder_exists
  ignore_errors: true
  tags: vim

- name: Vim Config | Download Webscope vim setup
  raw: git clone https://github.com/Webscope/webscope-vim.git ~/.webscope-vim
  when: webscope_vim_folder_exists.stdout.find('No such file or directory') != -1
  tags: vim

- name: Vim Config | Update vim plugins
  raw: cd ~/.webscope-vim && git submodule foreach git pull origin master
  tags: vim

- name: Vim Config | Check if ~/.vim folder exists
  raw: ls ~/.vim
  register: vim_folder_exists
  ignore_errors: true
  tags: vim

- name: Vimrc Config | Remove ~/.vim folder
  file: path=~/.vim
        state=absent
  when: vim_folder_exists.stdout.find('No such file or directory') == -1
  tags: vim

- name: Vim Config | Check if ~/.vimrc file exists
  raw: ls ~/.vimrc
  register: vimrc_exists
  ignore_errors: true
  tags: vim

- name: Vimrc Config | Remove ~/.vimrc file
  file: path=~/.vimrc
        state=absent
  when: vimrc_exists.stdout.find('No such file or directory') == -1
  tags: vim

- name: Vim Config | Setup vim config
  raw: cd ~/.webscope-vim && sh install.sh
  tags: vim

